import type { Category } from '../types'

export const ROUTES = {
  HOME: '/',
  SKILL: '/skill/:id',
  PROFILE: '/profile',
  FAVORITES: '/favorites',
  CREATE: '/create',
  LOGIN: '/login',
  REGISTER: '/register',
} as const

export const LOCAL_STORAGE_KEYS = {
  AUTH_USER: 'skillswap_auth_user',
  ACCOUNT: 'skillswap_account',
  CREATED_SKILLS: 'skillswap_created_skills',
  FAVORITES: 'skillswap_favorites',
  REQUESTS: 'skillswap_requests',
  THEME: 'skillswap_theme',
} as const

export const CATEGORIES_DATA: Category[] = [
  {
    id: '1',
    name: 'Бизнес и карьера',
    icon: 'business',
    subcategories: [
      { id: '101', name: 'Управление командой' },
      { id: '102', name: 'Маркетинг и реклама' },
      { id: '103', name: 'Продажи и переговоры' },
      { id: '104', name: 'Личный бренд' },
      { id: '105', name: 'Резюме и собеседование' },
      { id: '106', name: 'Тайм-менеджмент' },
      { id: '107', name: 'Проектное управление' },
      { id: '108', name: 'Предпринимательство' },
    ],
  },
  {
    id: '2',
    name: 'Творчество и искусство',
    icon: 'art',
    subcategories: [
      { id: '201', name: 'Рисование и иллюстрация' },
      { id: '202', name: 'Фотография' },
      { id: '203', name: 'Видеомонтаж' },
      { id: '204', name: 'Музыка и звук' },
      { id: '205', name: 'Актёрское мастерство' },
      { id: '206', name: 'Креативное письмо' },
      { id: '207', name: 'Арт-терапия' },
      { id: '208', name: 'Декор и DIY' },
    ],
  },
  {
    id: '3',
    name: 'Иностранные языки',
    icon: 'languages',
    subcategories: [
      { id: '301', name: 'Английский' },
      { id: '302', name: 'Французский' },
      { id: '303', name: 'Испанский' },
      { id: '304', name: 'Немецкий' },
      { id: '305', name: 'Китайский' },
      { id: '306', name: 'Японский' },
      { id: '307', name: 'Подготовка к экзаменам (IELTS, TOEFL)' },
    ],
  },
  {
    id: '4',
    name: 'Образование и развитие',
    icon: 'education',
    subcategories: [
      { id: '401', name: 'Личностное развитие' },
      { id: '402', name: 'Навыки обучения' },
      { id: '403', name: 'Когнитивные техники' },
      { id: '404', name: 'Скорочтение' },
      { id: '405', name: 'Навыки преподавания' },
      { id: '406', name: 'Коучинг' },
    ],
  },
  {
    id: '5',
    name: 'Дом и уют',
    icon: 'home',
    subcategories: [
      { id: '501', name: 'Уборка и организация' },
      { id: '502', name: 'Домашние финансы' },
      { id: '503', name: 'Приготовление еды' },
      { id: '504', name: 'Домашние растения' },
      { id: '505', name: 'Ремонт' },
      { id: '506', name: 'Хранение вещей' },
    ],
  },
  {
    id: '6',
    name: 'Здоровье и лайфстайл',
    icon: 'health',
    subcategories: [
      { id: '601', name: 'Йога и медитация' },
      { id: '602', name: 'Питание и ЗОЖ' },
      { id: '603', name: 'Ментальное здоровье' },
      { id: '604', name: 'Осознанность' },
      { id: '605', name: 'Физические тренировки' },
      { id: '606', name: 'Сон и восстановление' },
      { id: '607', name: 'Баланс жизни и работы' },
    ],
  },
]

export const MOCK_CITIES = [
  { id: '1', name: 'Москва' },
  { id: '2', name: 'Санкт-Петербург' },
  { id: '3', name: 'Казань' },
  { id: '4', name: 'Новосибирск' },
  { id: '5', name: 'Екатеринбург' },
  { id: '6', name: 'Красноярск' },
  { id: '7', name: 'Нижний Новгород' },
  { id: '8', name: 'Челябинск' },
  { id: '9', name: 'Уфа' },
  { id: '10', name: 'Краснодар' },
  { id: '11', name: 'Самара' },
  { id: '12', name: 'Ростов-на-Дону' },
  { id: '13', name: 'Омск' },
  { id: '14', name: 'Воронеж' },
  { id: '15', name: 'Пермь' },
  { id: '16', name: 'Волгоград' },
  { id: '17', name: 'Саратов' },
  { id: '18', name: 'Тюмень' },
  { id: '19', name: 'Тольятти' },
  { id: '20', name: 'Барнаул' },
  { id: '21', name: 'Ижевск' },
  { id: '22', name: 'Хабаровск' },
  { id: '23', name: 'Владивосток' },
  { id: '24', name: 'Ставрополь' },
  { id: '25', name: 'Ярославль' },
  { id: '26', name: 'Оренбург' },
  { id: '27', name: 'Рязань' },
  { id: '28', name: 'Чебоксары' },
  { id: '29', name: 'Калининград' },
  { id: '30', name: 'Пенза' },
  { id: '31', name: 'Липецк' },
  { id: '32', name: 'Сочи' },
  { id: '33', name: 'Сургут' },
  { id: '34', name: 'Астрахань' },
  { id: '35', name: 'Тверь' },
  { id: '36', name: 'Магнитогорск' },
  { id: '37', name: 'Брянск' },
  { id: '38', name: 'Смоленск' },
  { id: '39', name: 'Архангельск' },
  { id: '40', name: 'Кострома' },
  { id: '41', name: 'Новороссийск' },
]

export const GENDER_OPTIONS = [
  { value: '', label: 'Не указан' },
  { value: 'male', label: 'Мужской' },
  { value: 'female', label: 'Женский' },
] as const
