export const ROUTES = {
  HOME: '/',
  SKILL: '/skill/:id',
  PROFILE: '/profile',
  FAVORITES: '/favorites',
  CREATE: '/create',
  LOGIN: '/login',
  REGISTER: '/register',
} as const

export const SKILL_CATEGORIES = [
  'Программирование',
  'Дизайн',
  'Языки',
  'Музыка',
  'Спорт',
  'Кулинария',
  'Фото и видео',
  'Бизнес',
  'Другое',
] as const

export const LOCAL_STORAGE_KEYS = {
  AUTH_USER: 'skillswap_auth_user',
  FAVORITES: 'skillswap_favorites',
  REQUESTS: 'skillswap_requests',
  THEME: 'skillswap_theme',
} as const

export const MOCK_CITIES = [
  { id: '1', name: 'Москва' },
  { id: '2', name: 'Санкт-Петербург' },
  { id: '3', name: 'Казань' },
  { id: '4', name: 'Новосибирск' },
  { id: '5', name: 'Екатеринбург' },
  { id: '6', name: 'Красноярск' },
  { id: '7', name: 'Нижний Новгород' },
  { id: '8', name: 'Челябинск' },
  { id: '9', name: 'Уфа' },
  { id: '10', name: 'Краснодар' },
  { id: '11', name: 'Самара' },
  { id: '12', name: 'Ростов-на-Дону' },
  { id: '13', name: 'Омск' },
  { id: '14', name: 'Воронеж' },
  { id: '15', name: 'Пермь' },
  { id: '16', name: 'Волгоград' },
  { id: '17', name: 'Саратов' },
  { id: '18', name: 'Тюмень' },
  { id: '19', name: 'Тольятти' },
  { id: '20', name: 'Барнаул' },
  { id: '21', name: 'Ижевск' },
  { id: '22', name: 'Хабаровск' },
  { id: '23', name: 'Владивосток' },
  { id: '24', name: 'Ставрополь' },
  { id: '25', name: 'Ярославль' },
  { id: '26', name: 'Оренбург' },
  { id: '27', name: 'Рязань' },
  { id: '28', name: 'Чебоксары' },
  { id: '29', name: 'Калининград' },
  { id: '30', name: 'Пенза' },
  { id: '31', name: 'Липецк' },
  { id: '32', name: 'Сочи' },
  { id: '33', name: 'Сургут' },
  { id: '34', name: 'Астрахань' },
  { id: '35', name: 'Тверь' },
  { id: '36', name: 'Магнитогорск' },
  { id: '37', name: 'Брянск' },
  { id: '38', name: 'Смоленск' },
  { id: '39', name: 'Архангельск' },
  { id: '40', name: 'Кострома' },
  { id: '41', name: 'Новороссийск' },
] as const
